import type {
  Comment,
  Like,
  MediaItem,
  MediaItemWithOwner,
  UserWithNoPassword,
} from 'hybrid-types/DBTypes';
import {useCallback, useEffect, useState} from 'react';
import {fetchData} from '../utils/fetch-data';
import type {Credentials, RegisterCredentials} from '../types/LocalTypes';
import type {
  AvailableResponse,
  LoginResponse,
  MediaResponse,
  MessageResponse,
  UploadResponse,
  UserResponse,
} from 'hybrid-types/MessageTypes';

import {File} from 'expo-file-system';
import {useUpdateContext} from './ContextHooks';
import AsyncStorage from '@react-native-async-storage/async-storage';

const useMedia = (instance = false, ownFiles = false) => {
  const [mediaArray, setMediaArray] = useState<MediaItemWithOwner[]>([]);
  const {update} = useUpdateContext();
  // const {getMediaByTagName} = useTag();

  useEffect(() => {
    const getMedia = async () => {
      if (!instance) {
        return;
      }
      try {
        const endpoint = ownFiles ? '/media/bytoken' : '/media';

        const options = {
          method: 'GET',
          headers: {
            Authorization: 'Bearer ' + (await AsyncStorage.getItem('token')),
          },
        };

        const media = await fetchData<MediaItem[]>(
          process.env.EXPO_PUBLIC_MEDIA_API + endpoint,
          options,
        );

        // const media = await getMediaByTagName('defrtyhjuiklo');

        const mediaWithOwners = await Promise.all<MediaItemWithOwner>(
          media.map(async (item) => {
            try {
              const owner = await fetchData<UserWithNoPassword>(
                `${process.env.EXPO_PUBLIC_AUTH_API}/users/${item.user_id}`,
              );
              const mediaItemWithOwner: MediaItemWithOwner = {
                ...item,
                username: owner.username,
              };
              return mediaItemWithOwner;
            } catch (error) {
              console.error(error);
              return {
                ...item,
                username: 'not found',
              };
            }
          }),
        );
        setMediaArray(mediaWithOwners);
      } catch (error) {
        console.error(error);
      }
    };

    getMedia();
  }, [update]);

  const postMedia = async (
    file: UploadResponse,
    inputs: Record<string, string>,
    token: string,
  ) => {
    // create a suitable object for Media API,
    // the type is MediaItem without media_id, user_id, thumbnail, screenshots, and created_at. All those are generated by the API.
    const mediaData = {
      ...file.data,
      ...inputs,
    };
    const options = {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + token,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(mediaData),
    };
    // post the data to Media API and get the data as MediaResponse
    return fetchData<MediaResponse>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/media',
      options,
    );
  };

  return {mediaArray, postMedia};
};

const useAuthentication = () => {
  const postLogin = async (inputs: Credentials) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };
    const loginResult = await fetchData<LoginResponse>(
      process.env.EXPO_PUBLIC_AUTH_API + '/auth/login',
      fetchOptions,
    );
    // console.log(loginResult);
    return loginResult;
  };

  return {postLogin};
};

const useUser = () => {
  const resourceUrl = process.env.EXPO_PUBLIC_AUTH_API + '/users';

  const postRegister = async (inputs: RegisterCredentials) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };
    const registerResult = await fetchData(resourceUrl, fetchOptions);
    return registerResult;
  };

  const getUserByToken = useCallback(
    async (token: string) => {
      const options = {
        method: 'GET',
        headers: {
          Authorization: 'Bearer ' + token,
        },
      };
      return fetchData<UserResponse>(resourceUrl + '/token', options);
    },
    [resourceUrl],
  );

  const getUsernameAvailable = async (username: string) => {
    // fetch from endpoint /users/username/:username
    return fetchData<AvailableResponse>(`${resourceUrl}/username/${username}`);
  };

  const getEmailAvailable = async (email: string) => {
    // fetch from endpoint /users/email/:email
    return fetchData<AvailableResponse>(`${resourceUrl}/email/${email}`);
  };

  return {
    postRegister,
    getUserByToken,
    getUsernameAvailable,
    getEmailAvailable,
  };
};

const useFile = () => {
  const [loading, setLoading] = useState(false);
  const postFile = async (file: File, token: string) => {
    // create FormData object
    const formData = new FormData();
    // add file to FormData
    formData.append('file', file);
    // upload the file to file server and get the file data
    // return the file data. The type is UploadResponse
    const options = {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + token,
      },
      body: formData,
    };
    const result = await fetchData<UploadResponse>(
      process.env.EXPO_PUBLIC_UPLOAD_API + '/upload',
      options,
    );
    return result;
  };

  return {postFile, loading, setLoading};
};

const useLike = () => {
  const postLike = async (media_id: number, token: string) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + token,
      },
      body: JSON.stringify({media_id}),
    };
    return fetchData<MessageResponse>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/likes',
      fetchOptions,
    );
  };

  const deleteLike = async (like_id: number, token: string) => {
    // TODO: Send a DELETE request to /likes/:like_id with the token in the Authorization header.
    const fetchOptions = {
      method: 'DELETE',
      headers: {
        Authorization: 'Bearer ' + token,
      },
    };
    return fetchData<MessageResponse>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/likes/' + like_id,
      fetchOptions,
    );
  };

  const getCountByMediaId = async (media_id: number) => {
    // TODO: Send a GET request to /likes/count/:media_id to get the number of likes.
    return fetchData<{count: number}>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/likes/count/' + media_id,
    );
  };

  const getUserLike = async (media_id: number, token: string) => {
    // TODO: Send a GET request to /likes/bymedia/user/:media_id to get the user's like on the media.
    const fetchOptions = {
      method: 'GET',
      headers: {
        Authorization: 'Bearer ' + token,
      },
    };
    return fetchData<Like>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/likes/bymedia/user/' + media_id,
      fetchOptions,
    );
  };

  return {postLike, deleteLike, getCountByMediaId, getUserLike};
};

const useComment = () => {
  const postComment = async (
    comment_text: string,
    media_id: number,
    token: string,
  ) => {
    // Send a POST request to /comments with the comment object and the token in the Authorization header.
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + token,
      },
      body: JSON.stringify({media_id, comment_text}),
    };
    return fetchData<MessageResponse>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/comments',
      fetchOptions,
    );
  };

  const getCommentsByMediaId = async (id: number) => {
    // Send a GET request to /comments/bymedia/:media_id to get the comments.
    const comments = await fetchData<Comment[]>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/comments/bymedia/' + id,
    );
    // Send a GET requests to auth api and add usernames to all comments
    const commentsWithUsername = Promise.all<Comment & {username: string}>(
      comments.map(async (comment) => {
        const userInfo = await fetchData<UserWithNoPassword>(
          process.env.EXPO_PUBLIC_AUTH_API + '/users/' + comment.user_id,
        );
        return {...comment, username: userInfo.username};
      }),
    );
    return commentsWithUsername;
  };

  return {postComment, getCommentsByMediaId};
};

const useTag = () => {
  const postTag = async (media_id: number, tag_name: string, token: string) => {
    // Send a POST request to /tags with the tag object and the token in the Authorization header.
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + token,
      },
      body: JSON.stringify({media_id, tag_name}),
    };
    return fetchData<MessageResponse>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/tags',
      fetchOptions,
    );
  };

  const getMediaByTagName = async (tag_name: string) => {
    // Send a GET request to /tags/:tag_name to get the media items with the tag.
    return await fetchData<MediaItem[]>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/tags/' + tag_name,
    );
  };

  return {postTag, getMediaByTagName};
};

export {
  useMedia,
  useAuthentication,
  useUser,
  useFile,
  useLike,
  useComment,
  useTag,
};
